name: Reusable Azure Login

on:
  workflow_call:
    inputs:
      azure-subscription:
        description: 'Azure subscription ID'
        required: false
        type: string
      enable-az-ps-module:
        description: 'Enable Azure PowerShell module'
        required: false
        default: false
        type: boolean
    secrets:
      AZURE_CLIENT_ID:
        description: 'Azure client ID'
        required: true
      AZURE_TENANT_ID:
        description: 'Azure tenant ID'
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: 'Azure subscription ID'
        required: true

jobs:
  azure-login:
    name: Azure Authentication
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ inputs.azure-subscription || secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: ${{ inputs.enable-az-ps-module }}
          
      - name: Set Azure subscription
        if: ${{ inputs.azure-subscription }}
        run: |
          az account set --subscription "${{ inputs.azure-subscription }}"
          echo "✅ Azure subscription set to: ${{ inputs.azure-subscription }}"
          
      - name: Verify Azure authentication
        run: |
          az account show --output table
          echo "✅ Azure authentication successful"